"""The controlled vocabulary Component A extracts against.

Loads `vocabulary.json` — generated by `data/etl/export_vocabulary.py` from the
corpus itself — and builds the lookup index the extractor matches document text
against. No database, no network: the artifact is committed precisely so intake
can run with neither.

## The one rule

⚠️ Normalisation is used ONLY TO FIND A MATCH. What comes back out is always the
corpus's own spelling, byte-for-byte.

Everything downstream compares with exact, case-sensitive equality —
`rules.tag_overlap` intersects raw `set[str]`, and `corpus.fetch_candidates`
prefilters with the Postgres `&&` operator. A value that differs from the corpus
by one character does not score low, it fails to RETRIEVE: no candidate rows, no
comp set, and no error anywhere to say why.

How thin that ice is: `Free to Play` is a TAG and `Free To Play` is a GENRE.
Same words, different capitalisation, two different vocabularies. Emitting the
tag spelling into `sub_genres` matches nothing at all. This is why the indexes
are kept separate and why nothing here ever invents or re-cases a value.

## Aliases

Normalisation already absorbs most surface variation — punctuation, case, and
`&`/`and` — so `hand-drawn`, `Hand-Drawn` and `hand drawn` all reach
`Hand-drawn` with no alias needed. The table below is only for genuine
vocabulary gaps, where a writer's word is not a spelling variant of the corpus
term but a different term for it: nobody writes "Rogue-like" in a design
document, they write "roguelike".

Every alias target is verified against the loaded vocabulary at import. A typo
in the table raises immediately rather than silently extracting a value that can
never match a corpus row.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

VOCABULARY_PATH = Path(__file__).with_name("vocabulary.json")

#: Longest vocabulary entry in words, which is how wide the extractor's n-gram
#: scan has to be. Asserted against the artifact at import rather than hardcoded
#: on faith — a regenerated vocabulary with a longer entry must not silently
#: become unmatchable.
MAX_PHRASE_WORDS = 4

_PUNCT = re.compile(r"[^a-z0-9]+")
_SPACE = re.compile(r"\s+")


def normalise(text: str) -> str:
    """Casefold and strip punctuation, for MATCHING ONLY — never for output.

    `&` becomes `and` before punctuation is stripped, so the corpus's
    `Point & Click` and a document's "point and click" land on the same key
    instead of on `point click`.
    """
    lowered = text.casefold().replace("&", " and ")
    return _SPACE.sub(" ", _PUNCT.sub(" ", lowered)).strip()


def tokenise(text: str) -> list[str]:
    """Document text to normalised word tokens.

    Token-based rather than substring: matching `Dog` against the raw string
    would fire on "dogged", and `War` on "warehouse". A phrase is a run of
    consecutive tokens, so only whole words can match.
    """
    return normalise(text).split()


# --------------------------------------------------------------------------
# Aliases — writer's word -> corpus term
# --------------------------------------------------------------------------

#: Keyed by NORMALISED surface form; the value is the exact corpus string.
TAG_ALIASES: dict[str, str] = {
    "roguelike": "Rogue-like",
    "rogue like": "Rogue-like",
    "roguelite": "Rogue-lite",
    "rogue lite": "Rogue-lite",
    "scifi": "Sci-fi",
    "science fiction": "Sci-fi",
    "deckbuilder": "Deckbuilding",
    "deck builder": "Deckbuilding",
    "deck building": "Deckbuilding",
    "mmo": "Massively Multiplayer",
    "f2p": "Free to Play",
    "freetoplay": "Free to Play",
}

GENRE_ALIASES: dict[str, str] = {
    "mmo": "Massively Multiplayer",
    # ⚠️ Not a duplicate of the tag alias above — the genre vocabulary
    # capitalises this differently ("Free To Play"), and the two are compared
    # against different corpus columns.
    "f2p": "Free To Play",
    "free to play": "Free To Play",
}

#: ⚠️ Steam reports exactly three platforms, so this is the whole target space.
#: Consoles are DELIBERATELY absent: a pitch naming "Nintendo Switch" or
#: "consoles" has nowhere to land, and inventing a `Switch` value would emit
#: something no corpus row can match — scoring `target_platforms` against an
#: unmatchable set is worse than scoring it against the subset Steam knows.
#: The extractor drops what it cannot map and says so in the profile.
PLATFORM_ALIASES: dict[str, str] = {
    "pc": "Windows",
    "win": "Windows",
    "microsoft windows": "Windows",
    "mac": "macOS",
    "macos": "macOS",
    "mac os": "macOS",
    "os x": "macOS",
    "osx": "macOS",
    "apple": "macOS",
    "steamos": "Linux",
    "steam deck": "Linux",
    "gnu linux": "Linux",
}


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------


def _load() -> dict:
    try:
        return json.loads(VOCABULARY_PATH.read_text())
    except FileNotFoundError as exc:  # pragma: no cover — a broken deploy
        raise RuntimeError(
            f"❌ {VOCABULARY_PATH.name} is missing. It is a committed artifact; "
            "regenerate with `python3 data/etl/export_vocabulary.py`."
        ) from exc


def _index(rows: list[dict], aliases: dict[str, str]) -> dict[str, str]:
    """Normalised form -> exact corpus string, aliases layered on top.

    Aliases are applied last and deliberately win: `free to play` normalises to
    itself and would otherwise resolve to whichever spelling the corpus happens
    to hold in that column.
    """
    index = {normalise(row["value"]): row["value"] for row in rows}
    canonical = {row["value"] for row in rows}

    for surface, target in aliases.items():
        if target not in canonical:
            raise RuntimeError(
                f"❌ alias {surface!r} -> {target!r} is not in the corpus vocabulary. "
                "Aliases must resolve to a real corpus value or extraction emits "
                "something no row can match."
            )
        index[surface] = target
    return index


_DATA = _load()

#: Corpus frequency, canonical spelling -> title count. The extractor ranks by
#: this to pick `primary_genre` when a document matches several.
TAG_COUNTS: dict[str, int] = {r["value"]: r["count"] for r in _DATA["tags"]}
GENRE_COUNTS: dict[str, int] = {r["value"]: r["count"] for r in _DATA["genres"]}
PLATFORM_COUNTS: dict[str, int] = {r["value"]: r["count"] for r in _DATA["platforms"]}

_AFFINITY: dict[str, list[dict]] = _DATA["genre_affinity"]

_TAG_INDEX = _index(_DATA["tags"], TAG_ALIASES)
_GENRE_INDEX = _index(_DATA["genres"], GENRE_ALIASES)
_PLATFORM_INDEX = _index(_DATA["platforms"], PLATFORM_ALIASES)

_widest = max(len(key.split()) for key in (*_TAG_INDEX, *_GENRE_INDEX, *_PLATFORM_INDEX))
if _widest > MAX_PHRASE_WORDS:  # pragma: no cover — only after a vocabulary change
    raise RuntimeError(
        f"❌ vocabulary contains a {_widest}-word entry but MAX_PHRASE_WORDS is "
        f"{MAX_PHRASE_WORDS}; the extractor's scan would never reach it."
    )


# --------------------------------------------------------------------------
# Lookup
# --------------------------------------------------------------------------


def lookup_tag(phrase: str) -> str | None:
    """Exact corpus tag for a normalised phrase, or None."""
    return _TAG_INDEX.get(phrase)


def lookup_genre(phrase: str) -> str | None:
    return _GENRE_INDEX.get(phrase)


def lookup_platform(phrase: str) -> str | None:
    return _PLATFORM_INDEX.get(phrase)


def genre_affinity(tag: str) -> list[tuple[str, float]]:
    """Genres a tag co-occurs with in the corpus, most associated first.

    Measured, not asserted: 91.6% of `Shooter` titles are filed under Action.
    ➡️ `data/etl/export_vocabulary.py` for why this is needed at all.
    """
    return [(row["genre"], row["share"]) for row in _AFFINITY.get(tag, ())]


def corpus_titles() -> int:
    """How many titles the vocabulary was derived from — reported in assumptions."""
    return int(_DATA["corpus_titles"])
